repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: go
        args: ["fmt", "./pkg/...", "./cmd/..."]
        language: system
        files: \.go$
        pass_filenames: false

      - id: go-vet
        name: go vet
        entry: go
        args: ["vet", "./pkg/...", "./cmd/..."]
        language: system
        files: \.go$
        pass_filenames: false
