# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task --list-all
    silent: true
  check:
    cmds:
      - go mod tidy
      - go mod verify
      - go fmt ./pkg/... ./integration/... ./cmd/...
      - go vet ./pkg/... ./integration/... ./cmd/...
      - task: test:unit
  build:
    cmds:
    - go build -o bin/ryan main.go
  run:
    cmds:
      - task: build
      - ./bin/ryan
  test:
    cmds:
      - go test ./pkg/... ./integration/... ./cmd/...
  
  test:unit:
    desc: Run only unit tests (excludes integration tests)
    cmds:
      - go test ./pkg/... ./cmd/...
  
  test:integration:
    desc: Run integration tests against real Ollama API
    cmds:
      - go test -v ./integration/...
    env:
      OLLAMA_URL: '{{default "https://ollama.kitty-tetra.ts.net" .OLLAMA_URL}}'
      OLLAMA_TEST_MODEL: '{{default "qwen2.5-coder:1.5b-base" .OLLAMA_TEST_MODEL}}'
  
  test:all:
    desc: Run all tests (unit and integration)
    cmds:
      - task: test
      - task: test:integration

  build:model-tester:
    desc: Build model compatibility testing tool
    cmds:
      - go build -o bin/model-tester ./cmd/model-tester

  test:models:primary:
    desc: Test primary models for tool calling compatibility
    deps: [build:model-tester]
    cmds:
      - ./bin/model-tester -models primary -url {{default "http://localhost:11434" .OLLAMA_URL}}

  test:models:secondary:
    desc: Test secondary models for tool calling compatibility  
    deps: [build:model-tester]
    cmds:
      - ./bin/model-tester -models secondary -url {{default "http://localhost:11434" .OLLAMA_URL}}

  test:models:all:
    desc: Test all recommended models for tool calling compatibility
    deps: [build:model-tester]
    cmds:
      - ./bin/model-tester -models all -url {{default "http://localhost:11434" .OLLAMA_URL}}

  test:models:custom:
    desc: Test custom list of models (set MODELS="model1,model2,model3")
    deps: [build:model-tester]
    cmds:
      - ./bin/model-tester -models "{{.MODELS}}" -url {{default "http://localhost:11434" .OLLAMA_URL}}