# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task --list-all
    silent: true
  check:
    cmds:
      - go mod tidy
      - go mod verify
      - go fmt ./pkg/... ./cmd/...
      - go vet ./pkg/... ./cmd/...
      - task: test

  lint:
    desc: Run linting checks on the codebase (includes pre-commit)
    cmds:
      - go fmt ./pkg/... ./cmd/...
      - go vet ./pkg/... ./cmd/...
      - uvx pre-commit run --all-files
  build:
    cmds:
    - go build -o bin/ryan main.go
  run:
    cmds:
      - task: build
      - ./bin/ryan
  test:
    cmds:
      - mkdir -p coverage
      - go test -coverprofile=coverage/coverage.out ./pkg/... ./cmd/...
  test:integration:
    desc: Run integration tests for CLI and agents
    cmds:
      - go clean -testcache
      - go test -v -count=1 ./integration/...
