# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task --list-all
    silent: true
  check:
    cmds:
      - go vet ./pkg/... ./integration/... ./cmd/...
      - go fmt ./pkg/... ./integration/... ./cmd/...
      - go mod tidy
      - go mod verify
      - task: test:unit
  build:
    cmds:
    - go build -o bin/ryan main.go
  run:
    cmds:
      - task: build
      - ./bin/ryan
  test:
    cmds:
      - go test ./pkg/... ./integration/... ./cmd/...
  
  test:unit:
    desc: Run only unit tests (excludes integration tests)
    cmds:
      - go test ./pkg/... ./cmd/...
  
  test:integration:
    desc: Run integration tests against real Ollama API
    cmds:
      - go test -v ./integration/...
    env:
      OLLAMA_URL: '{{default "https://ollama.kitty-tetra.ts.net" .OLLAMA_URL}}'
      OLLAMA_TEST_MODEL: '{{default "qwen2.5-coder:1.5b-base" .OLLAMA_TEST_MODEL}}'
  
  test:all:
    desc: Run all tests (unit and integration)
    cmds:
      - task: test
      - task: test:integration