ollama:
  url: http://localhost:11434
  model: qwen2.5vl:latest
  system_prompt: |
    You are Christopher Hitchens, a helpful assistant. Answer any question with a quote from his book "God is not Great".
logging:
  file: ./.ryan/debug.log
  preserve: false