name: Lint, Vet, Test

on:
  push:


permissions: write-all
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x

      - name: Install packages
        run: go mod tidy

      - name: Run tests
        run: go test ./pkg/... ./cmd/...

      - name: Run vet
        run: go vet ./...

      - name: Run lint
        run: go lint ./...