name: Integration Tests

on:
  workflow_dispatch:
    inputs:
      model:
        description: 'Ollama model to use for testing'
        required: false
        default: 'smollm2:135m'
        type: choice
        options:
          - smollm2:135m
          - smollm2:360m
          - qwen2.5:0.5b
          - tinyllama:1.1b

jobs:
  integration:
    runs-on: ubuntu-latest
    services:
      ollama:
        image: ollama/ollama:latest
        ports:
          - 11434:11434
        options: >-
          --health-cmd "ollama list"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
          --health-start-period 30s

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.x

      - name: Wait for Ollama to be Ready
        run: |
          echo "Waiting for Ollama to be ready..."
          for i in {1..30}; do
            if curl -s http://localhost:11434/api/tags > /dev/null 2>&1; then
              echo "Ollama is ready after $i seconds"
              break
            fi
            echo "Attempt $i: Ollama not ready, waiting..."
            sleep 2
          done

          # Final check
          if ! curl -s http://localhost:11434/api/tags > /dev/null 2>&1; then
            echo "Ollama failed to start properly"
            exit 1
          fi

      - name: Pull Ollama Model
        run: |
          MODEL="${{ github.event.inputs.model || 'smollm2:135m' }}"
          echo "Pulling model: $MODEL"

          # Pull the model
          curl -X POST http://localhost:11434/api/pull \
            -H "Content-Type: application/json" \
            -d "{\"name\": \"$MODEL\"}" \
            --fail-with-body

          # Verify model is loaded
          echo "Verifying model is available..."
          curl -s http://localhost:11434/api/tags | grep -q "$MODEL" || {
            echo "Model $MODEL not found in available models"
            curl -s http://localhost:11434/api/tags | jq .
            exit 1
          }

          echo "Model $MODEL is ready"

      - name: Run Integration Tests
        env:
          OLLAMA_HOST: http://localhost:11434
          OLLAMA_DEFAULT_MODEL: ${{ github.event.inputs.model || 'smollm2:135m' }}
          OLLAMA_URL: http://localhost:11434
        run: |
          MODEL="${{ github.event.inputs.model || 'smollm2:135m' }}"
          echo "Running integration tests with OLLAMA_HOST=$OLLAMA_HOST"
          echo "Using model: $MODEL"
          go test -v -count=1 -timeout=5m ./integration/...

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            coverage/
            *.log
            integration/*.log
